In [2]:
%load_ext autoreload
%autoreload 2
main_dir = r'../../..'
data_path = main_dir+'/data'
import sys
sys.path.append(main_dir)
from typing import List, Set, Dict, Optional, Any, Tuple, Type, Union

from BayDS.lib.pipeline import *
from BayDS.lib.io import *
import os

In [3]:
data_dir = f'{main_dir}/Snapshots/1/05-LabelEncoded'
new_id_data_dir = f'{main_dir}/Snapshots/1/NewId'
p = Pipeline(working_folder=f'{main_dir}/Snapshots/1/06-Untitled')

p.add_node(LoaderNode, None, 'data',
           params={
               'input_directory': data_dir,
               'file': 'label_encoded_data.pkl'
           })
p.add_node(LoaderNode, None, 'numerical_columns',
           params={
               'input_directory': data_dir,
               'file': 'numerical_columns.yaml'
           })
p.add_node(LoaderNode, None, 'categorical_columns',
           params={
               'input_directory': data_dir,
               'file': 'categorical_columns.yaml'
           })
p.add_node(LoaderNode, None, 'TransactionAmt_Agg',
           params={
               'input_directory': new_id_data_dir,
               'file': 'TransactionAmt_Agg.pkl'
           })

p.add_node(LoaderNode, None, 'C5_Agg',
           params={
               'input_directory': new_id_data_dir,
               'file': 'C5_Agg.pkl'
           })

p.add_node(LoaderNode, None, 'C8_Agg',
           params={
               'input_directory': new_id_data_dir,
               'file': 'C8_Agg.pkl'
           })
p.run()

---------------------------
0: LoaderNode [2019-09-21 21:32:57]
params:
 {'input_directory': '../../../Snapshots/1/05-LabelEncoded', 'file': 'label_encoded_data.pkl'}
---------------------------
1: LoaderNode [2019-09-21 21:33:01]
params:
 {'input_directory': '../../../Snapshots/1/05-LabelEncoded', 'file': 'numerical_columns.yaml'}
---------------------------
2: LoaderNode [2019-09-21 21:33:01]
params:
 {'input_directory': '../../../Snapshots/1/05-LabelEncoded', 'file': 'categorical_columns.yaml'}
---------------------------
3: LoaderNode [2019-09-21 21:33:01]
params:
 {'input_directory': '../../../Snapshots/1/NewId', 'file': 'TransactionAmt_Agg.pkl'}
---------------------------
4: LoaderNode [2019-09-21 21:33:01]
params:
 {'input_directory': '../../../Snapshots/1/NewId', 'file': 'C5_Agg.pkl'}
---------------------------
5: LoaderNode [2019-09-21 21:33:02]
params:
 {'input_directory': '../../../Snapshots/1/NewId', 'file': 'C8_Agg.pkl'}

In [4]:
p.data['data'].shape #1097231

(1091152, 590)

In [2]:
p.add_node(JoinNode,
           ('data', 'TransactionAmt_Agg'),
           'data',
           params={
               'on': 'TransactionID'
           })

p.add_node(JoinNode,
           ('data', 'C5_Agg'),
           'data',
           params={
               'on': 'TransactionID'
           })
p.add_node(JoinNode,
           ('data', 'C8_Agg'),
           'data',
           params={
               'on': 'TransactionID'
           })
p.add_node(EraserNode, params={
    'remove_keys': ['C5_Agg', 'C8_Agg', 'TransactionAmt_Agg']
})
p.add_node(ReduceMemoryUsageNode,
           'data', 'data',
           params={
               'verbose': True
           })

p.save()
p.run(verbose=True)
p.save_data()

---------------------------
0: LoaderNode [2019-09-21 21:08:50]
params:
 {'input_directory': '../../../Snapshots/1/05-LabelEncoded', 'file': 'label_encoded_data.pkl'}
---------------------------
1: LoaderNode [2019-09-21 21:08:56]
params:
 {'input_directory': '../../../Snapshots/1/05-LabelEncoded', 'file': 'numerical_columns.yaml'}
---------------------------
2: LoaderNode [2019-09-21 21:08:56]
params:
 {'input_directory': '../../../Snapshots/1/05-LabelEncoded', 'file': 'categorical_columns.yaml'}
---------------------------
3: LoaderNode [2019-09-21 21:08:56]
params:
 {'input_directory': '../../../Snapshots/1/NewId', 'file': 'TransactionAmt_Agg.pkl'}
---------------------------
4: LoaderNode [2019-09-21 21:08:56]
params:
 {'input_directory': '../../../Snapshots/1/NewId', 'file': 'C5_Agg.pkl'}
---------------------------
5: LoaderNode [2019-09-21 21:08:56]
params:
 {'input_directory': '../../../Snapshots/1/NewId', 'file': 'C8_Agg.pkl'}
---------------------------
6: JoinNode [2019-09-21 21:08:57]
params:
 {'on': 'TransactionID'}
---------------------------
7: JoinNode [2019-09-21 21:09:38]
params:
 {'on': 'TransactionID'}
---------------------------
8: JoinNode [2019-09-21 21:10:19]
params:
 {'on': 'TransactionID'}
---------------------------
9: EraserNode [2019-09-21 21:10:23]
params:
 {'remove_keys': ['C5_Agg', 'C8_Agg', 'TransactionAmt_Agg']}
---------------------------
10: ReduceMemoryUsageNode [2019-09-21 21:10:23]
params:
 {'verbose': True}
Column isFraud: int8 -> int8, na_count=0, n_uniq=3
Column TransactionDT: int32 -> int32, na_count=0, n_uniq=1062085
Column TransactionAmt: float32 -> float32, na_count=0, n_uniq=29660
Column ProductCD: int32 -> int8, na_count=0, n_uniq=5
Column card1: int32 -> int16, na_count=0, n_uniq=17078
Column card2: int32 -> int16, na_count=0, n_uniq=502
Column card3: int32 -> int16, na_count=0, n_uniq=134
Column card4: int32 -> int8, na_count=0, n_uniq=5
Column card5: int32 -> int16, na_count=0, n_uniq=139
Column card6: int32 -> int8, na_count=0, n_uniq=5
Column addr1: int32 -> int16, na_count=0, n_uniq=442
Column addr2: int32 -> int8, na_count=0, n_uniq=94
Column dist1: float32 -> float32, na_count=645994, n_uniq=2738
Column dist2: float32 -> float32, na_count=1024405, n_uniq=2347
Column P_emaildomain: int32 -> int8, na_count=0, n_uniq=61
Column R_emaildomain: int32 -> int8, na_count=0, n_uniq=61
Column C1: float32 -> float32, na_count=3, n_uniq=2188
Column C2: float32 -> float32, na_count=3, n_uniq=1784
Column C3: float16 -> float16, na_count=3, n_uniq=33
Column C4: float32 -> float32, na_count=3, n_uniq=1533
Column C5: float16 -> float16, na_count=3, n_uniq=354
Column C6: float32 -> float32, na_count=3, n_uniq=1573
Column C7: float32 -> float32, na_count=3, n_uniq=1336
Column C8: float32 -> float32, na_count=3, n_uniq=1419
Column C9: float16 -> float16, na_count=3, n_uniq=361
Column C10: float32 -> float32, na_count=3, n_uniq=1384
Column C11: float32 -> float32, na_count=3, n_uniq=1833
Column C12: float32 -> float32, na_count=3, n_uniq=1531
Column C13: float32 -> float32, na_count=4748, n_uniq=1692
Column C14: float16 -> float16, na_count=3, n_uniq=1151
Column D1: float16 -> float16, na_count=7273, n_uniq=643
Column D2: float16 -> float16, na_count=513873, n_uniq=643
Column D3: float16 -> float16, na_count=464508, n_uniq=889
Column D4: float16 -> float16, na_count=245364, n_uniq=1070
Column D5: float16 -> float16, na_count=533060, n_uniq=962
Column D6: float16 -> float16, na_count=900480, n_uniq=1077
Column D7: float16 -> float16, na_count=999436, n_uniq=906
Column D8: float32 -> float32, na_count=949434, n_uniq=17055
Column D9: float16 -> float16, na_count=949434, n_uniq=25
Column D10: float16 -> float16, na_count=88090, n_uniq=1076
Column D11: float16 -> float16, na_count=454939, n_uniq=888
Column D12: float16 -> float16, na_count=964518, n_uniq=869
Column D13: float16 -> float16, na_count=913046, n_uniq=828
Column D14: float16 -> float16, na_count=921048, n_uniq=1036
Column D15: float16 -> float16, na_count=100733, n_uniq=1092
Column M1: int32 -> int8, na_count=0, n_uniq=3
Column M2: int32 -> int8, na_count=0, n_uniq=3
Column M3: int32 -> int8, na_count=0, n_uniq=3
Column M4: int32 -> int8, na_count=0, n_uniq=4
Column M5: int32 -> int8, na_count=0, n_uniq=3
Column M6: int32 -> int8, na_count=0, n_uniq=3
Column M7: int32 -> int8, na_count=0, n_uniq=3
Column M8: int32 -> int8, na_count=0, n_uniq=3
Column M9: int32 -> int8, na_count=0, n_uniq=3
Column V1: float16 -> float16, na_count=454939, n_uniq=3
Column V2: float16 -> float16, na_count=454939, n_uniq=13
Column V3: float16 -> float16, na_count=454939, n_uniq=13
Column V4: float16 -> float16, na_count=454939, n_uniq=11
Column V5: float16 -> float16, na_count=454939, n_uniq=12
Column V6: float16 -> float16, na_count=454939, n_uniq=15
Column V7: float16 -> float16, na_count=454939, n_uniq=15
Column V8: float16 -> float16, na_count=454939, n_uniq=13
Column V9: float16 -> float16, na_count=454939, n_uniq=13
Column V10: float16 -> float16, na_count=454939, n_uniq=7
Column V11: float16 -> float16, na_count=454939, n_uniq=9
Column V12: float16 -> float16, na_count=88184, n_uniq=6
Column V13: float16 -> float16, na_count=88184, n_uniq=8
Column V14: float16 -> float16, na_count=88184, n_uniq=3
Column V15: float16 -> float16, na_count=88184, n_uniq=14
Column V16: float16 -> float16, na_count=88184, n_uniq=24
Column V17: float16 -> float16, na_count=88184, n_uniq=17
Column V18: float16 -> float16, na_count=88184, n_uniq=17
Column V19: float16 -> float16, na_count=88184, n_uniq=14
Column V20: float16 -> float16, na_count=88184, n_uniq=24
Column V21: float16 -> float16, na_count=88184, n_uniq=7
Column V22: float16 -> float16, na_count=88184, n_uniq=10
Column V23: float16 -> float16, na_count=88184, n_uniq=17
Column V24: float16 -> float16, na_count=88184, n_uniq=27
Column V25: float16 -> float16, na_count=88184, n_uniq=14
Column V26: float16 -> float16, na_count=88184, n_uniq=24
Column V27: float16 -> float16, na_count=88184, n_uniq=9
Column V28: float16 -> float16, na_count=88184, n_uniq=9
Column V29: float16 -> float16, na_count=88184, n_uniq=7
Column V30: float16 -> float16, na_count=88184, n_uniq=10
Column V31: float16 -> float16, na_count=88184, n_uniq=14
Column V32: float16 -> float16, na_count=88184, n_uniq=24
Column V33: float16 -> float16, na_count=88184, n_uniq=14
Column V34: float16 -> float16, na_count=88184, n_uniq=24
Column V35: float16 -> float16, na_count=245413, n_uniq=6
Column V36: float16 -> float16, na_count=245413, n_uniq=8
Column V37: float16 -> float16, na_count=245413, n_uniq=56
Column V38: float16 -> float16, na_count=245413, n_uniq=56
Column V39: float16 -> float16, na_count=245413, n_uniq=23
Column V40: float16 -> float16, na_count=245413, n_uniq=26
Column V41: float16 -> float16, na_count=245413, n_uniq=3
Column V42: float16 -> float16, na_count=245413, n_uniq=10
Column V43: float16 -> float16, na_count=245413, n_uniq=13
Column V44: float16 -> float16, na_count=245413, n_uniq=50
Column V45: float16 -> float16, na_count=245413, n_uniq=71
Column V46: float16 -> float16, na_count=245413, n_uniq=10
Column V47: float16 -> float16, na_count=245413, n_uniq=14
Column V48: float16 -> float16, na_count=245413, n_uniq=7
Column V49: float16 -> float16, na_count=245413, n_uniq=9
Column V50: float16 -> float16, na_count=245413, n_uniq=9
Column V51: float16 -> float16, na_count=245413, n_uniq=10
Column V52: float16 -> float16, na_count=245413, n_uniq=13
Column V53: float16 -> float16, na_count=89505, n_uniq=7
Column V54: float16 -> float16, na_count=89505, n_uniq=9
Column V55: float16 -> float16, na_count=89505, n_uniq=51
Column V56: float16 -> float16, na_count=89505, n_uniq=53
Column V57: float16 -> float16, na_count=89505, n_uniq=8
Column V58: float16 -> float16, na_count=89505, n_uniq=12
Column V59: float16 -> float16, na_count=89505, n_uniq=18
Column V60: float16 -> float16, na_count=89505, n_uniq=19
Column V61: float16 -> float16, na_count=89505, n_uniq=8
Column V62: float16 -> float16, na_count=89505, n_uniq=12
Column V63: float16 -> float16, na_count=89505, n_uniq=10
Column V64: float16 -> float16, na_count=89505, n_uniq=12
Column V65: float16 -> float16, na_count=89505, n_uniq=3
Column V66: float16 -> float16, na_count=89505, n_uniq=10

Column V67: float16 -> float16, na_count=89505, n_uniq=12
Column V68: float16 -> float16, na_count=89505, n_uniq=9
Column V69: float16 -> float16, na_count=89505, n_uniq=7
Column V70: float16 -> float16, na_count=89505, n_uniq=10
Column V71: float16 -> float16, na_count=89505, n_uniq=8
Column V72: float16 -> float16, na_count=89505, n_uniq=12
Column V73: float16 -> float16, na_count=89505, n_uniq=10
Column V74: float16 -> float16, na_count=89505, n_uniq=12
Column V75: float16 -> float16, na_count=100794, n_uniq=7
Column V76: float16 -> float16, na_count=100794, n_uniq=9
Column V77: float16 -> float16, na_count=100794, n_uniq=82
Column V78: float16 -> float16, na_count=100794, n_uniq=82
Column V79: float16 -> float16, na_count=100794, n_uniq=9
Column V80: float16 -> float16, na_count=100794, n_uniq=21
Column V81: float16 -> float16, na_count=100794, n_uniq=21
Column V82: float16 -> float16, na_count=100794, n_uniq=9
Column V83: float16 -> float16, na_count=100794, n_uniq=9
Column V84: float16 -> float16, na_count=100794, n_uniq=12
Column V85: float16 -> float16, na_count=100794, n_uniq=12
Column V86: float16 -> float16, na_count=100794, n_uniq=82
Column V87: float16 -> float16, na_count=100794, n_uniq=82
Column V88: float16 -> float16, na_count=100794, n_uniq=3
Column V89: float16 -> float16, na_count=100794, n_uniq=9
Column V90: float16 -> float16, na_count=100794, n_uniq=7
Column V91: float16 -> float16, na_count=100794, n_uniq=10
Column V92: float16 -> float16, na_count=100794, n_uniq=9
Column V93: float16 -> float16, na_count=100794, n_uniq=9
Column V94: float16 -> float16, na_count=100794, n_uniq=4
Column V95: float16 -> float16, na_count=314, n_uniq=882
Column V96: float16 -> float16, na_count=314, n_uniq=1411
Column V97: float16 -> float16, na_count=314, n_uniq=977
Column V98: float16 -> float16, na_count=314, n_uniq=14
Column V99: float16 -> float16, na_count=314, n_uniq=90
Column V100: float16 -> float16, na_count=314, n_uniq=32
Column V101: float16 -> float16, na_count=314, n_uniq=871
Column V102: float16 -> float16, na_count=314, n_uniq=1286
Column V103: float16 -> float16, na_count=314, n_uniq=929
Column V104: float16 -> float16, na_count=314, n_uniq=61
Column V105: float16 -> float16, na_count=314, n_uniq=101
Column V106: float16 -> float16, na_count=314, n_uniq=82
Column V107: float16 -> float16, na_count=314, n_uniq=3
Column V108: float16 -> float16, na_count=314, n_uniq=10
Column V109: float16 -> float16, na_count=314, n_uniq=10
Column V110: float16 -> float16, na_count=314, n_uniq=10
Column V111: float16 -> float16, na_count=314, n_uniq=11
Column V112: float16 -> float16, na_count=314, n_uniq=11
Column V113: float16 -> float16, na_count=314, n_uniq=11
Column V114: float16 -> float16, na_count=314, n_uniq=11
Column V115: float16 -> float16, na_count=314, n_uniq=11
Column V116: float16 -> float16, na_count=314, n_uniq=11
Column V117: float16 -> float16, na_count=314, n_uniq=5
Column V118: float16 -> float16, na_count=314, n_uniq=5
Column V119: float16 -> float16, na_count=314, n_uniq=5
Column V120: float16 -> float16, na_count=314, n_uniq=6
Column V121: float16 -> float16, na_count=314, n_uniq=6
Column V122: float16 -> float16, na_count=314, n_uniq=6
Column V123: float16 -> float16, na_count=314, n_uniq=15
Column V124: float16 -> float16, na_count=314, n_uniq=15
Column V125: float16 -> float16, na_count=314, n_uniq=15
Column V126: float32 -> float32, na_count=314, n_uniq=15075
Column V127: float32 -> float32, na_count=314, n_uniq=33418
Column V128: float32 -> float32, na_count=314, n_uniq=20428
Column V129: float32 -> float32, na_count=314, n_uniq=2628
Column V130: float32 -> float32, na_count=314, n_uniq=16201
Column V131: float32 -> float32, na_count=314, n_uniq=5775
Column V132: float32 -> float32, na_count=314, n_uniq=9269
Column V133: float32 -> float32, na_count=314, n_uniq=13605
Column V134: float32 -> float32, na_count=314, n_uniq=11271
Column V135: float32 -> float32, na_count=314, n_uniq=6248
Column V136: float32 -> float32, na_count=314, n_uniq=8174
Column V137: float32 -> float32, na_count=314, n_uniq=7108
Column V138: float16 -> float16, na_count=940980, n_uniq=24
Column V139: float16 -> float16, na_count=940980, n_uniq=35
Column V140: float16 -> float16, na_count=940980, n_uniq=61
Column V141: float16 -> float16, na_count=940980, n_uniq=8
Column V142: float16 -> float16, na_count=940980, n_uniq=13
Column V143: float16 -> float16, na_count=940704, n_uniq=871
Column V144: float16 -> float16, na_count=940704, n_uniq=87
Column V145: float16 -> float16, na_count=940704, n_uniq=299
Column V146: float16 -> float16, na_count=940980, n_uniq=26
Column V147: float16 -> float16, na_count=940980, n_uniq=28
Column V148: float16 -> float16, na_count=940980, n_uniq=22
Column V149: float16 -> float16, na_count=940980, n_uniq=22
Column V150: float32 -> float32, na_count=940704, n_uniq=3294
Column V151: float16 -> float16, na_count=940704, n_uniq=59
Column V152: float16 -> float16, na_count=940704, n_uniq=45
Column V153: float16 -> float16, na_count=940980, n_uniq=20
Column V154: float16 -> float16, na_count=940980, n_uniq=20
Column V155: float16 -> float16, na_count=940980, n_uniq=26
Column V156: float16 -> float16, na_count=940980, n_uniq=26
Column V157: float16 -> float16, na_count=940980, n_uniq=26
Column V158: float16 -> float16, na_count=940980, n_uniq=26
Column V159: float32 -> float32, na_count=940704, n_uniq=12622
Column V160: float32 -> float32, na_count=940704, n_uniq=17151
Column V161: float32 -> float32, na_count=940980, n_uniq=106
Column V162: float32 -> float32, na_count=940980, n_uniq=289
Column V163: float32 -> float32, na_count=940980, n_uniq=154
Column V164: float32 -> float32, na_count=940704, n_uniq=2746
Column V165: float32 -> float32, na_count=940704, n_uniq=3789
Column V166: float32 -> float32, na_count=940704, n_uniq=2261
Column V167: float16 -> float16, na_count=822520, n_uniq=874
Column V168: float16 -> float16, na_count=822520, n_uniq=966
Column V169: float16 -> float16, na_count=822663, n_uniq=41
Column V170: float16 -> float16, na_count=822663, n_uniq=65
Column V171: float16 -> float16, na_count=822663, n_uniq=70
Column V172: float16 -> float16, na_count=822520, n_uniq=39
Column V173: float16 -> float16, na_count=822520, n_uniq=11
Column V174: float16 -> float16, na_count=822663, n_uniq=10
Column V175: float16 -> float16, na_count=822663, n_uniq=24
Column V176: float16 -> float16, na_count=822520, n_uniq=241
Column V177: float16 -> float16, na_count=822520, n_uniq=863
Column V178: float16 -> float16, na_count=822520, n_uniq=1237
Column V179: float16 -> float16, na_count=822520, n_uniq=922
Column V180: float16 -> float16, na_count=822663, n_uniq=181
Column V181: float16 -> float16, na_count=822520, n_uniq=87
Column V182: float16 -> float16, na_count=822520, n_uniq=127
Column V183: float16 -> float16, na_count=822520, n_uniq=108
Column V184: float16 -> float16, na_count=822663, n_uniq=18
Column V185: float16 -> float16, na_count=822663, n_uniq=33
Column V186: float16 -> float16, na_count=822520, n_uniq=41
Column V187: float16 -> float16, na_count=822520, n_uniq=216
Column V188: float16 -> float16, na_count=822663, n_uniq=46
Column V189: float16 -> float16, na_count=822663, n_uniq=46
Column V190: float16 -> float16, na_count=822520, n_uniq=226
Column V191: float16 -> float16, na_count=822520, n_uniq=23
Column V192: float16 -> float16, na_count=822520, n_uniq=46
Column V193: float16 -> float16, na_count=822520, n_uniq=39
Column V194: float16 -> float16, na_count=822663, n_uniq=9
Column V195: float16 -> float16, na_count=822663, n_uniq=20
Column V196: float16 -> float16, na_count=822520, n_uniq=43
Column V197: float16 -> float16, na_count=822663, n_uniq=16
Column V198: float16 -> float16, na_count=822663, n_uniq=30
Column V199: float16 -> float16, na_count=822520, n_uniq=226
Column V200: float16 -> float16, na_count=822663, n_uniq=49
Column V201: float16 -> float16, na_count=822663, n_uniq=57
Column V202: float32 -> float32, na_count=822520, n_uniq=18556
Column V203: float32 -> float32, na_count=822520, n_uniq=26206
Column V204: float32 -> float32, na_count=822520, n_uniq=22286
Column V205: float32 -> float32, na_count=822520, n_uniq=3653

Column V206: float32 -> float32, na_count=822520, n_uniq=2964
Column V207: float32 -> float32, na_count=822520, n_uniq=5247
Column V208: float32 -> float32, na_count=822663, n_uniq=4073
Column V209: float32 -> float32, na_count=822663, n_uniq=5915
Column V210: float32 -> float32, na_count=822663, n_uniq=4664
Column V211: float32 -> float32, na_count=822520, n_uniq=12978
Column V212: float32 -> float32, na_count=822520, n_uniq=15569
Column V213: float32 -> float32, na_count=822520, n_uniq=14522
Column V214: float32 -> float32, na_count=822520, n_uniq=3807
Column V215: float32 -> float32, na_count=822520, n_uniq=4652
Column V216: float32 -> float32, na_count=822520, n_uniq=4186
Column V217: float16 -> float16, na_count=841703, n_uniq=305
Column V218: float16 -> float16, na_count=841703, n_uniq=402
Column V219: float16 -> float16, na_count=841703, n_uniq=380
Column V220: float16 -> float16, na_count=820164, n_uniq=45
Column V221: float16 -> float16, na_count=820164, n_uniq=86
Column V222: float16 -> float16, na_count=820164, n_uniq=294
Column V223: float16 -> float16, na_count=841703, n_uniq=18
Column V224: float16 -> float16, na_count=841703, n_uniq=92
Column V225: float16 -> float16, na_count=841703, n_uniq=38
Column V226: float16 -> float16, na_count=841703, n_uniq=114
Column V227: float16 -> float16, na_count=820164, n_uniq=69
Column V228: float16 -> float16, na_count=841703, n_uniq=241
Column V229: float16 -> float16, na_count=841703, n_uniq=264
Column V230: float16 -> float16, na_count=841703, n_uniq=264
Column V231: float16 -> float16, na_count=841703, n_uniq=295
Column V232: float16 -> float16, na_count=841703, n_uniq=339
Column V233: float16 -> float16, na_count=841703, n_uniq=334
Column V234: float16 -> float16, na_count=820164, n_uniq=309
Column V235: float16 -> float16, na_count=841703, n_uniq=25
Column V236: float16 -> float16, na_count=841703, n_uniq=56
Column V237: float16 -> float16, na_count=841703, n_uniq=41
Column V238: float16 -> float16, na_count=820164, n_uniq=25
Column V239: float16 -> float16, na_count=820164, n_uniq=25
Column V240: float16 -> float16, na_count=841703, n_uniq=8
Column V241: float16 -> float16, na_count=841703, n_uniq=7
Column V242: float16 -> float16, na_count=841703, n_uniq=29
Column V243: float16 -> float16, na_count=841703, n_uniq=59
Column V244: float16 -> float16, na_count=841703, n_uniq=35
Column V245: float16 -> float16, na_count=820164, n_uniq=70
Column V246: float16 -> float16, na_count=841703, n_uniq=226
Column V247: float16 -> float16, na_count=841703, n_uniq=20
Column V248: float16 -> float16, na_count=841703, n_uniq=32
Column V249: float16 -> float16, na_count=841703, n_uniq=24
Column V250: float16 -> float16, na_count=820164, n_uniq=20
Column V251: float16 -> float16, na_count=820164, n_uniq=20
Column V252: float16 -> float16, na_count=841703, n_uniq=26
Column V253: float16 -> float16, na_count=841703, n_uniq=106
Column V254: float16 -> float16, na_count=841703, n_uniq=56
Column V255: float16 -> float16, na_count=820164, n_uniq=53
Column V256: float16 -> float16, na_count=820164, n_uniq=57
Column V257: float16 -> float16, na_count=841703, n_uniq=226
Column V258: float16 -> float16, na_count=841703, n_uniq=271
Column V259: float16 -> float16, na_count=820164, n_uniq=78
Column V260: float16 -> float16, na_count=841703, n_uniq=16
Column V261: float16 -> float16, na_count=841703, n_uniq=74
Column V262: float16 -> float16, na_count=841703, n_uniq=33
Column V263: float32 -> float32, na_count=841703, n_uniq=18164
Column V264: float32 -> float32, na_count=841703, n_uniq=23767
Column V265: float32 -> float32, na_count=841703, n_uniq=20789
Column V266: float32 -> float32, na_count=841703, n_uniq=3609
Column V267: float32 -> float32, na_count=841703, n_uniq=6114
Column V268: float32 -> float32, na_count=841703, n_uniq=4558
Column V269: float32 -> float32, na_count=841703, n_uniq=226
Column V270: float32 -> float32, na_count=820164, n_uniq=3817
Column V271: float32 -> float32, na_count=820164, n_uniq=4792
Column V272: float32 -> float32, na_count=820164, n_uniq=4155
Column V273: float32 -> float32, na_count=841703, n_uniq=12798
Column V274: float32 -> float32, na_count=841703, n_uniq=15039
Column V275: float32 -> float32, na_count=841703, n_uniq=14073
Column V276: float32 -> float32, na_count=841703, n_uniq=3728
Column V277: float32 -> float32, na_count=841703, n_uniq=4191
Column V278: float32 -> float32, na_count=841703, n_uniq=3946
Column V279: float16 -> float16, na_count=15, n_uniq=882
Column V280: float16 -> float16, na_count=15, n_uniq=976
Column V281: float16 -> float16, na_count=7273, n_uniq=32
Column V282: float16 -> float16, na_count=7273, n_uniq=65
Column V283: float16 -> float16, na_count=7273, n_uniq=70
Column V284: float16 -> float16, na_count=15, n_uniq=14
Column V285: float16 -> float16, na_count=15, n_uniq=97
Column V286: float16 -> float16, na_count=15, n_uniq=10
Column V287: float16 -> float16, na_count=15, n_uniq=33
Column V288: float16 -> float16, na_count=7273, n_uniq=12
Column V289: float16 -> float16, na_count=7273, n_uniq=14
Column V290: float16 -> float16, na_count=15, n_uniq=62
Column V291: float16 -> float16, na_count=15, n_uniq=316
Column V292: float16 -> float16, na_count=15, n_uniq=193
Column V293: float16 -> float16, na_count=15, n_uniq=871
Column V294: float16 -> float16, na_count=15, n_uniq=1287
Column V295: float16 -> float16, na_count=15, n_uniq=929
Column V296: float16 -> float16, na_count=7273, n_uniq=181
Column V297: float16 -> float16, na_count=16, n_uniq=87
Column V298: float16 -> float16, na_count=16, n_uniq=127
Column V299: float16 -> float16, na_count=16, n_uniq=108
Column V300: float16 -> float16, na_count=7274, n_uniq=16
Column V301: float16 -> float16, na_count=7274, n_uniq=16
Column V302: float16 -> float16, na_count=16, n_uniq=18
Column V303: float16 -> float16, na_count=16, n_uniq=22
Column V304: float16 -> float16, na_count=16, n_uniq=19
Column V305: float16 -> float16, na_count=16, n_uniq=3
Column V306: float32 -> float32, na_count=16, n_uniq=25167
Column V307: float32 -> float32, na_count=16, n_uniq=54376
Column V308: float32 -> float32, na_count=16, n_uniq=35105
Column V309: float32 -> float32, na_count=16, n_uniq=6149
Column V310: float32 -> float32, na_count=16, n_uniq=26436
Column V311: float32 -> float32, na_count=16, n_uniq=4599
Column V312: float32 -> float32, na_count=16, n_uniq=11342
Column V313: float32 -> float32, na_count=7274, n_uniq=8028
Column V314: float32 -> float32, na_count=7274, n_uniq=16286
Column V315: float32 -> float32, na_count=7274, n_uniq=10142
Column V316: float32 -> float32, na_count=16, n_uniq=14910
Column V317: float32 -> float32, na_count=16, n_uniq=22471
Column V318: float32 -> float32, na_count=16, n_uniq=18524
Column V319: float32 -> float32, na_count=16, n_uniq=8132
Column V320: float32 -> float32, na_count=16, n_uniq=10786
Column V321: float32 -> float32, na_count=16, n_uniq=9342
Column V322: float16 -> float16, na_count=939932, n_uniq=882
Column V323: float16 -> float16, na_count=939932, n_uniq=1412
Column V324: float16 -> float16, na_count=939932, n_uniq=977
Column V325: float16 -> float16, na_count=939932, n_uniq=14
Column V326: float16 -> float16, na_count=939932, n_uniq=46
Column V327: float16 -> float16, na_count=939932, n_uniq=33
Column V328: float16 -> float16, na_count=939932, n_uniq=87
Column V329: float16 -> float16, na_count=939932, n_uniq=127
Column V330: float16 -> float16, na_count=939932, n_uniq=108
Column V331: float32 -> float32, na_count=939932, n_uniq=2093
Column V332: float32 -> float32, na_count=939932, n_uniq=3227
Column V333: float32 -> float32, na_count=939932, n_uniq=2491
Column V334: float32 -> float32, na_count=939932, n_uniq=221
Column V335: float32 -> float32, na_count=939932, n_uniq=1019
Column V336: float32 -> float32, na_count=939932, n_uniq=504
Column V337: float32 -> float32, na_count=939932, n_uniq=438
Column V338: float32 -> float32, na_count=939932, n_uniq=794
Column V339: float32 -> float32, na_count=939932, n_uniq=625
Column NanTransactionCount: int16 -> int16, na_count=0, n_uniq=263
Column id_01: float16 -> float16, na_count=812784, n_uniq=90
Column id_02: float32 -> float32, na_count=821037, n_uniq=197523
Column id_03: float16 -> float16, na_count=965881, n_uniq=26

Column id_04: float16 -> float16, na_count=965881, n_uniq=17
Column id_05: float16 -> float16, na_count=827240, n_uniq=98
Column id_06: float16 -> float16, na_count=827240, n_uniq=102
Column id_07: float16 -> float16, na_count=1088130, n_uniq=93
Column id_08: float16 -> float16, na_count=1088130, n_uniq=98
Column id_09: float16 -> float16, na_count=949434, n_uniq=52
Column id_10: float16 -> float16, na_count=949434, n_uniq=68
Column id_11: float32 -> float32, na_count=821129, n_uniq=413
Column id_12: int32 -> int8, na_count=0, n_uniq=3
Column id_13: int32 -> int8, na_count=0, n_uniq=56
Column id_14: int32 -> int8, na_count=0, n_uniq=29
Column id_15: int32 -> int8, na_count=0, n_uniq=4
Column id_16: int32 -> int8, na_count=0, n_uniq=3
Column id_17: int32 -> int8, na_count=0, n_uniq=128
Column id_18: int32 -> int8, na_count=0, n_uniq=20
Column id_19: int32 -> int16, na_count=0, n_uniq=569
Column id_20: int32 -> int16, na_count=0, n_uniq=548
Column id_21: int32 -> int16, na_count=0, n_uniq=734
Column id_22: int32 -> int8, na_count=0, n_uniq=36
Column id_23: int32 -> int8, na_count=0, n_uniq=4
Column id_24: int32 -> int8, na_count=0, n_uniq=18
Column id_25: int32 -> int16, na_count=0, n_uniq=441
Column id_26: int32 -> int8, na_count=0, n_uniq=116
Column id_27: int32 -> int8, na_count=0, n_uniq=3
Column id_28: int32 -> int8, na_count=0, n_uniq=3
Column id_29: int32 -> int8, na_count=0, n_uniq=3
Column id_30: int32 -> int8, na_count=0, n_uniq=88
Column id_31: int32 -> int16, na_count=0, n_uniq=173
Column id_32: int32 -> int8, na_count=0, n_uniq=7
Column id_33: int32 -> int16, na_count=0, n_uniq=462
Column id_34: int32 -> int8, na_count=0, n_uniq=5
Column id_35: int32 -> int8, na_count=0, n_uniq=3
Column id_36: int32 -> int8, na_count=0, n_uniq=3
Column id_37: int32 -> int8, na_count=0, n_uniq=3
Column id_38: int32 -> int8, na_count=0, n_uniq=3
Column DeviceType: int32 -> int8, na_count=0, n_uniq=3
Column DeviceInfo: int32 -> int16, na_count=0, n_uniq=2796
Column NanIdentityCount: float16 -> float16, na_count=812784, n_uniq=34
Column Date: datetime64[ns] -> datetime64[ns], na_count=0, n_uniq=1062085
Column Weekdays: int64 -> int8, na_count=0, n_uniq=7
Column Hours: int64 -> int8, na_count=0, n_uniq=24
Column Days: int64 -> int8, na_count=0, n_uniq=31
Column isNight: int32 -> int8, na_count=0, n_uniq=2
Column DT_M: int64 -> int8, na_count=0, n_uniq=12
Column DT_W: int64 -> int8, na_count=0, n_uniq=53
Column DT_D: int64 -> int16, na_count=0, n_uniq=363
Column id_02_to_mean_card1: float32 -> float32, na_count=821037, n_uniq=269639
Column id_02_to_mean_card4: float32 -> float32, na_count=822340, n_uniq=231252
Column id_02_to_std_card1: float32 -> float32, na_count=824941, n_uniq=269749
Column id_02_to_std_card4: float32 -> float32, na_count=822340, n_uniq=231282
Column D15_to_mean_card1: float16 -> float16, na_count=109962, n_uniq=11907
Column D15_to_mean_card4: float16 -> float16, na_count=105373, n_uniq=2480
Column D15_to_std_card1: float16 -> float16, na_count=110839, n_uniq=11061
Column D15_to_std_card4: float16 -> float16, na_count=105373, n_uniq=2459
Column D15_to_mean_addr1: float16 -> float16, na_count=228150, n_uniq=6751
Column D15_to_std_addr1: float16 -> float16, na_count=228189, n_uniq=6207
Column TransactionAmt_to_mean_card1: float32 -> float32, na_count=0, n_uniq=288857
Column TransactionAmt_to_mean_card4: float32 -> float32, na_count=4663, n_uniq=39244
Column TransactionAmt_to_std_card1: float32 -> float32, na_count=4028, n_uniq=291450
Column TransactionAmt_to_std_card4: float32 -> float32, na_count=4663, n_uniq=39242
Column TransactionAmt_decimal: int32 -> int16, na_count=0, n_uniq=1000
Column nulls1: int64 -> int16, na_count=0, n_uniq=308
Column lastest_browser: int32 -> int8, na_count=0, n_uniq=2
Column device_name: int32 -> int8, na_count=0, n_uniq=15
Column device_version: int32 -> int16, na_count=0, n_uniq=380
Column OS_id_30: int32 -> int8, na_count=0, n_uniq=8
Column version_id_30: int32 -> int8, na_count=0, n_uniq=49
Column browser_id_31: int32 -> int8, na_count=0, n_uniq=43
Column version_id_31: int32 -> int8, na_count=0, n_uniq=46
Column screen_width: object -> object, na_count=0, n_uniq=248
Column screen_height: object -> object, na_count=0, n_uniq=217
Column had_id: int32 -> int8, na_count=0, n_uniq=1
Column TransactionAmt_Log: float32 -> float32, na_count=0, n_uniq=29660
Column card1_count_full: int64 -> int16, na_count=0, n_uniq=682
Column Transaction_day_of_week: float64 -> int8, na_count=0, n_uniq=7
Column Transaction_hour: float64 -> int8, na_count=0, n_uniq=24
Column id_02__id_20: int32 -> int32, na_count=0, n_uniq=269769
Column id_02__D8: int32 -> int32, na_count=0, n_uniq=258982
Column D11__DeviceInfo: int32 -> int16, na_count=0, n_uniq=3683
Column DeviceInfo__P_emaildomain: int32 -> int16, na_count=0, n_uniq=8958
Column P_emaildomain__C2: int32 -> int16, na_count=0, n_uniq=6784
Column card2__dist1: int32 -> int16, na_count=0, n_uniq=31297
Column card1__card5: int32 -> int16, na_count=0, n_uniq=18795
Column card2__id_20: int32 -> int16, na_count=0, n_uniq=9222
Column card5__P_emaildomain: int32 -> int16, na_count=0, n_uniq=1573
Column addr1__card1: int32 -> int32, na_count=0, n_uniq=55270
Column id_01_count_dist: int64 -> int32, na_count=0, n_uniq=45
Column id_31_count_dist: int64 -> int32, na_count=0, n_uniq=139
Column id_33_count_dist: int64 -> int32, na_count=0, n_uniq=107
Column id_36_count_dist: int64 -> int32, na_count=0, n_uniq=3
Column card2_count_full: int64 -> int32, na_count=0, n_uniq=368
Column card3_count_full: int64 -> int32, na_count=0, n_uniq=75
Column card4_count_full: int64 -> int32, na_count=0, n_uniq=5
Column card5_count_full: int64 -> int32, na_count=0, n_uniq=77
Column card6_count_full: int64 -> int32, na_count=0, n_uniq=5
Column addr1_count_full: int64 -> int32, na_count=0, n_uniq=111
Column addr2_count_full: int64 -> int32, na_count=0, n_uniq=31
Column id_36_count_full: int64 -> int32, na_count=0, n_uniq=3
Column M_sum: int8 -> int8, na_count=0, n_uniq=1
Column M_na: int8 -> int8, na_count=0, n_uniq=9
Column ProductCD_target_mean: float64 -> float16, na_count=0, n_uniq=5
Column M4_target_mean: float64 -> float16, na_count=517270, n_uniq=4
Column uid: int32 -> int16, na_count=0, n_uniq=18770
Column uid2: int32 -> int16, na_count=0, n_uniq=18833
Column uid3: int32 -> int32, na_count=0, n_uniq=58666
Column card1_TransactionAmt_mean: float64 -> float32, na_count=0, n_uniq=11885
Column card1_TransactionAmt_std: float64 -> float32, na_count=4028, n_uniq=11416
Column card2_TransactionAmt_mean: float64 -> float32, na_count=17541, n_uniq=502
Column card2_TransactionAmt_std: float64 -> float32, na_count=17541, n_uniq=502
Column card3_TransactionAmt_mean: float64 -> float32, na_count=4567, n_uniq=131
Column card3_TransactionAmt_std: float64 -> float32, na_count=4582, n_uniq=118
Column card5_TransactionAmt_mean: float64 -> float32, na_count=8795, n_uniq=129
Column card5_TransactionAmt_std: float64 -> float32, na_count=8815, n_uniq=113
Column uid_TransactionAmt_mean: float64 -> float32, na_count=0, n_uniq=12529
Column uid_TransactionAmt_std: float64 -> float32, na_count=4966, n_uniq=11986
Column uid2_TransactionAmt_mean: float64 -> float32, na_count=0, n_uniq=12558
Column uid2_TransactionAmt_std: float64 -> float32, na_count=5000, n_uniq=12008
Column uid3_TransactionAmt_mean: float64 -> float32, na_count=0, n_uniq=26419
Column uid3_TransactionAmt_std: float64 -> float32, na_count=23385, n_uniq=25866
Column card1_fq_enc: int64 -> int16, na_count=0, n_uniq=682
Column card2_fq_enc: int64 -> int32, na_count=0, n_uniq=368
Column card3_fq_enc: int64 -> int32, na_count=0, n_uniq=75
Column card5_fq_enc: int64 -> int32, na_count=0, n_uniq=77
Column C1_fq_enc: int64 -> int32, na_count=0, n_uniq=210
Column C2_fq_enc: int64 -> int32, na_count=0, n_uniq=203
Column C3_fq_enc: int64 -> int32, na_count=0, n_uniq=12
Column C4_fq_enc: int64 -> int32, na_count=0, n_uniq=76
Column C5_fq_enc: int64 -> int32, na_count=0, n_uniq=215
Column C6_fq_enc: int64 -> int32, na_count=0, n_uniq=175
Column C7_fq_enc: int64 -> int32, na_count=0, n_uniq=68
Column C8_fq_enc: int64 -> int32, na_count=0, n_uniq=83
Column C9_fq_enc: int64 -> int32, na_count=0, n_uniq=168

Column C10_fq_enc: int64 -> int32, na_count=0, n_uniq=91
Column C11_fq_enc: int64 -> int32, na_count=0, n_uniq=184
Column C12_fq_enc: int64 -> int32, na_count=0, n_uniq=73
Column C13_fq_enc: int64 -> int32, na_count=0, n_uniq=290
Column C14_fq_enc: int64 -> int32, na_count=0, n_uniq=179
Column D1_fq_enc: int64 -> int32, na_count=0, n_uniq=472
Column D2_fq_enc: int64 -> int32, na_count=0, n_uniq=467
Column D3_fq_enc: int64 -> int32, na_count=0, n_uniq=303
Column D4_fq_enc: int64 -> int32, na_count=0, n_uniq=575
Column D5_fq_enc: int64 -> int32, na_count=0, n_uniq=351
Column D6_fq_enc: int64 -> int32, na_count=0, n_uniq=196
Column D7_fq_enc: int64 -> int32, na_count=0, n_uniq=144
Column D8_fq_enc: int64 -> int32, na_count=0, n_uniq=178
Column addr1_fq_enc: int64 -> int32, na_count=0, n_uniq=111
Column addr2_fq_enc: int64 -> int32, na_count=0, n_uniq=31
Column dist1_fq_enc: int64 -> int32, na_count=0, n_uniq=248
Column dist2_fq_enc: int64 -> int32, na_count=0, n_uniq=201
Column P_emaildomain_fq_enc: int64 -> int32, na_count=0, n_uniq=60
Column R_emaildomain_fq_enc: int64 -> int32, na_count=0, n_uniq=58
Column DeviceInfo_fq_enc: int64 -> int32, na_count=0, n_uniq=209
Column id_30_fq_enc: int64 -> int32, na_count=0, n_uniq=85
Column version_id_30_fq_enc: int64 -> int32, na_count=0, n_uniq=48
Column version_id_31_fq_enc: int64 -> int32, na_count=0, n_uniq=46
Column id_33_fq_enc: int64 -> int32, na_count=0, n_uniq=107
Column uid_fq_enc: int64 -> int16, na_count=0, n_uniq=682
Column uid2_fq_enc: int64 -> int16, na_count=0, n_uniq=682
Column uid3_fq_enc: int64 -> int16, na_count=0, n_uniq=658
Column DT_M_total: int64 -> int32, na_count=0, n_uniq=12
Column DT_W_total: int64 -> int32, na_count=0, n_uniq=53
Column DT_D_total: int64 -> int16, na_count=0, n_uniq=332
Column card1_DT_M: float64 -> float32, na_count=0, n_uniq=2587
Column card2_DT_M: float64 -> float32, na_count=0, n_uniq=1983
Column card3_DT_M: float64 -> float32, na_count=0, n_uniq=436
Column card5_DT_M: float64 -> float32, na_count=0, n_uniq=555
Column uid_DT_M: float64 -> float32, na_count=0, n_uniq=2608
Column uid2_DT_M: float64 -> float32, na_count=0, n_uniq=2606
Column uid3_DT_M: float64 -> float32, na_count=0, n_uniq=2055
Column card1_DT_W: float64 -> float32, na_count=0, n_uniq=5277
Column card2_DT_W: float64 -> float32, na_count=0, n_uniq=4846
Column card3_DT_W: float64 -> float32, na_count=0, n_uniq=1086
Column card5_DT_W: float64 -> float32, na_count=0, n_uniq=1727
Column uid_DT_W: float64 -> float32, na_count=0, n_uniq=5280
Column uid2_DT_W: float64 -> float32, na_count=0, n_uniq=5279
Column uid3_DT_W: float64 -> float32, na_count=0, n_uniq=3771
Column card1_DT_D: float64 -> float32, na_count=0, n_uniq=10762
Column card2_DT_D: float64 -> float32, na_count=0, n_uniq=14057
Column card3_DT_D: float64 -> float32, na_count=0, n_uniq=3280
Column card5_DT_D: float64 -> float32, na_count=0, n_uniq=6817
Column uid_DT_D: float64 -> float32, na_count=0, n_uniq=10738
Column uid2_DT_D: float64 -> float32, na_count=0, n_uniq=10738
Column uid3_DT_D: float64 -> float32, na_count=0, n_uniq=7439
Column P_emaildomain_bin: int32 -> int8, na_count=0, n_uniq=10
Column P_emaildomain_suffix: int32 -> int8, na_count=0, n_uniq=9
Column R_emaildomain_bin: int32 -> int8, na_count=0, n_uniq=10
Column R_emaildomain_suffix: int32 -> int8, na_count=0, n_uniq=9
Column OS: int32 -> int8, na_count=0, n_uniq=9
Column OSVersion: int32 -> int8, na_count=0, n_uniq=88
Column Browser: int32 -> int8, na_count=0, n_uniq=24
Column BrowserVersion: object -> object, na_count=833386, n_uniq=54
Column BrowserAge: float64 -> float64, na_count=1098294, n_uniq=1
Column card_id: int32 -> int16, na_count=0, n_uniq=19213
Column TransactionAmt_by_new_card_id_ws1d_to_mean: float64 -> float64, na_count=0, n_uniq=319407
Column TransactionAmt_by_new_card_id_ws1d_to_std: float64 -> float64, na_count=611674, n_uniq=392706
Column TransactionAmt_by_new_card_id_ws2d_to_mean: float64 -> float64, na_count=0, n_uniq=376792
Column TransactionAmt_by_new_card_id_ws2d_to_std: float64 -> float64, na_count=547886, n_uniq=449069
Column TransactionAmt_by_new_card_id_ws3d_to_mean: float64 -> float64, na_count=0, n_uniq=410315
Column TransactionAmt_by_new_card_id_ws3d_to_std: float64 -> float64, na_count=508178, n_uniq=483234
Column TransactionAmt_by_new_card_id_ws7d_to_mean: float64 -> float64, na_count=0, n_uniq=481689
Column TransactionAmt_by_new_card_id_ws7d_to_std: float64 -> float64, na_count=410029, n_uniq=562682
Column TransactionAmt_by_new_card_id_ws30d_to_mean: float64 -> float64, na_count=0, n_uniq=621173
Column TransactionAmt_by_new_card_id_ws30d_to_std: float64 -> float64, na_count=234351, n_uniq=713344
Column TransactionAmt_by_new_card_id_ws5_to_mean: float64 -> float64, na_count=0, n_uniq=542342
Column TransactionAmt_by_new_card_id_ws5_to_std: float64 -> float64, na_count=144441, n_uniq=758472
Column TransactionAmt_by_new_card_id_ws10_to_mean: float64 -> float64, na_count=0, n_uniq=689349
Column TransactionAmt_by_new_card_id_ws10_to_std: float64 -> float64, na_count=144441, n_uniq=805591
Column TransactionAmt_by_new_card_id_ws100_to_mean: float64 -> float64, na_count=0, n_uniq=768496
Column TransactionAmt_by_new_card_id_ws100_to_std: float64 -> float64, na_count=144441, n_uniq=821037
Column C5_by_new_card_id_ws1d_to_mean: float64 -> float64, na_count=578822, n_uniq=11015
Column C5_by_new_card_id_ws1d_to_std: float64 -> float64, na_count=820556, n_uniq=62951
Column C5_by_new_card_id_ws2d_to_mean: float64 -> float64, na_count=545881, n_uniq=16860
Column C5_by_new_card_id_ws2d_to_std: float64 -> float64, na_count=770603, n_uniq=74929
Column C5_by_new_card_id_ws3d_to_mean: float64 -> float64, na_count=527467, n_uniq=21493
Column C5_by_new_card_id_ws3d_to_std: float64 -> float64, na_count=741342, n_uniq=81493
Column C5_by_new_card_id_ws7d_to_mean: float64 -> float64, na_count=491543, n_uniq=34965
Column C5_by_new_card_id_ws7d_to_std: float64 -> float64, na_count=674543, n_uniq=97224
Column C5_by_new_card_id_ws30d_to_mean: float64 -> float64, na_count=443415, n_uniq=67376
Column C5_by_new_card_id_ws30d_to_std: float64 -> float64, na_count=531360, n_uniq=129973
Column C5_by_new_card_id_ws5_to_mean: float64 -> float64, na_count=514119, n_uniq=22887
Column C5_by_new_card_id_ws5_to_std: float64 -> float64, na_count=519272, n_uniq=78031
Column C5_by_new_card_id_ws10_to_mean: float64 -> float64, na_count=453852, n_uniq=30156
Column C5_by_new_card_id_ws10_to_std: float64 -> float64, na_count=485805, n_uniq=98251
Column C5_by_new_card_id_ws100_to_mean: float64 -> float64, na_count=405036, n_uniq=51214
Column C5_by_new_card_id_ws100_to_std: float64 -> float64, na_count=463912, n_uniq=138369
Column C8_by_new_card_id_ws1d_to_mean: float64 -> float64, na_count=730203, n_uniq=18791
Column C8_by_new_card_id_ws1d_to_std: float64 -> float64, na_count=789568, n_uniq=101429
Column C8_by_new_card_id_ws2d_to_mean: float64 -> float64, na_count=704503, n_uniq=28735
Column C8_by_new_card_id_ws2d_to_std: float64 -> float64, na_count=758039, n_uniq=113258
Column C8_by_new_card_id_ws3d_to_mean: float64 -> float64, na_count=689284, n_uniq=35791
Column C8_by_new_card_id_ws3d_to_std: float64 -> float64, na_count=735698, n_uniq=119169
Column C8_by_new_card_id_ws7d_to_mean: float64 -> float64, na_count=656530, n_uniq=56008
Column C8_by_new_card_id_ws7d_to_std: float64 -> float64, na_count=688550, n_uniq=131839
Column C8_by_new_card_id_ws30d_to_mean: float64 -> float64, na_count=607955, n_uniq=94887
Column C8_by_new_card_id_ws30d_to_std: float64 -> float64, na_count=635432, n_uniq=153805
Column C8_by_new_card_id_ws5_to_mean: float64 -> float64, na_count=699703, n_uniq=7253
Column C8_by_new_card_id_ws5_to_std: float64 -> float64, na_count=645758, n_uniq=56480
Column C8_by_new_card_id_ws10_to_mean: float64 -> float64, na_count=650405, n_uniq=10552
Column C8_by_new_card_id_ws10_to_std: float64 -> float64, na_count=624155, n_uniq=67620
Column C8_by_new_card_id_ws100_to_mean: float64 -> float64, na_count=565539, n_uniq=31869
Column C8_by_new_card_id_ws100_to_std: float64 -> float64, na_count=591825, n_uniq=108995
Mem. usage decreased from 2841.76 Mb to 2157.80 Mb (24.1% reduction)
Saving data

Saving numerical_columns
Saving categorical_columns